config/routes.rb
Gratefuleaf::Application.routes.draw do

  namespace(:admin){ resources :leaves }
  namespace(:admin){ resources :users }

  match '/login' => 'user_sessions#new'
  match '/logout' => 'user_sessions#destroy'
  resources :user_sessions

  resources :users

  match 'leaves/stats' => 'leaves#stats'
  resources :leaves

  root :to => 'landing#index'

end

app/controllers/admin/leaves_controller.rb
class Admin::LeavesController < ApplicationController
  def index
    @leaves = Leaf.all
  end

  def show
    @leaf = Leaf.find(params[:id])
  end

  def new
    @leaf = Leaf.new
  end

  def create
    @leaf = Leaf.new(params[:leaf])
    if @leaf.save
      redirect_to [:admin, @leaf], :notice => "Successfully created leaf."
    else
      render :action => 'new'
    end
  end

  def edit
    @leaf = Leaf.find(params[:id])
  end

  def update
    @leaf = Leaf.find(params[:id])
    if @leaf.update_attributes(params[:leaf])
      redirect_to [:admin, @leaf], :notice  => "Successfully updated leaf."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @leaf = Leaf.find(params[:id])
    @leaf.destroy
    redirect_to admin_leaves_url, :notice => "Successfully destroyed leaf."
  end
end

app/controllers/leaves_controller.rb
class LeavesController < ApplicationController

  # only members have access to leaf sections
  before_filter :require_login

  def index
    if params[:tagged]
      tags = Tag.where("name = ?", params[:tagged])
      @leaves = tags.map do |tag|
        tag.leaf
      end
    else
      @leaves = current_user.leaves.reverse
    end

    @leaves_by_day = @leaves.group_by { |leaf| leaf.created_at.beginning_of_day }
  end


  def stats
    leaves = Leaf.count(
      :conditions => ["created_at >= ?", 14.days.ago],
      :group => "DATE(created_at)"
    )

    leaves_array = []
    14.downto(0) do |d|
      # Mon, 28 Jan 2013
      date = d.days.ago.strftime('%a, %d %b %Y').to_date
      leaves_array << (leaves[date] || 0)
    end


    @h = LazyHighCharts::HighChart.new('graph') do |f|
      f.options[:chart][:type] = "column"
      f.options[:chart][:inverted] = false
      f.options[:chart][:backgroundColor] = '#D0A34F'
      f.options[:legend][:enabled] = false
      f.options[:title][:text] = "Leaves in the Past 14 Days"
      f.options[:plotOptions] = {column: 
                                  {
                                    shadow: false, 
                                    borderWidth: 0, 
                                    pointInterval: 1.day, 
                                    pointStart: 14.days.ago
                                  }
                                }
      f.xAxis(:type => 'datetime', :labels => {:align => 'center'}, :dateTimeLabelFormats => { day: '%b %e' })
      f.yAxis(:title => {:text => 'Leaves'}, :allowDecimals => false, :gridLineWidth => 0, :lineWidth => 1)

      f.series(:name=>'Leaves', :data=>leaves_array, :color => '#426226')
    end
  end

  def new
    @leaf = Leaf.new
  end
  
  def show
    @leaf = Leaf.find(params[:id])
  end

  def create
    @leaf = current_user.leaves.new(params[:leaf])

    # extract user mentions
    mentions = []
    @leaf.content.scan(/(?:\s|^)(?:@(?!(?:\d+|\w+?_|_\w+?)(?:\s|$)))(\w+)(?=\s|$)/i) do |match|
      mentions.push(match.first)
    end
    # TODO: do something with mentions

    Leaf.transaction do
      if @leaf.save
        flash[:notice] = "Leaf created successfully."
        redirect_to :action => 'index'
      else
        render :action => 'new'
      end
    end
  end

  def destroy
    @leaf = Leaf.find(params[:id])

    if @leaf.photo_file_name
      current_user.substract_points(3)
    else
      current_user.substract_points(2)
    end

    @leaf.destroy
    redirect_to leaves_url, :notice => "Successfully destroyed leaf."
  end

  private

  def require_login
    unless current_user
      redirect_to login_url
    end
  end

end

app/helpers/admin/leaves_helper.rb
module Admin::LeavesHelper
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/views/leaves/index.html.erb
<div class="row leaf-feed">
  <div class="seven columns">
    <% if params[:tagged] %>
      <h2>Tagged as: <%= params[:tagged] %></h2>
    <% end %>
    <table>
      <% @leaves_by_day.each do |day, leaves| %>
        <tr>
          <td colspan=3>
            <div class="day-header">
              <h3><%= day.strftime("%A, %b %d, %Y") %></h3>
            </div>
          </td>
        </tr>
        <% leaves.each do |leaf| %>
          <tr>
            <td>
              <div class="leaf">
                <%= link_to leaf.created_at.strftime("%-I:%M %p"), leaf_path(leaf) %><br /><%= image_tag leaf.photo.url(:thumb) if leaf.has_photo %>
                <%= leaf.content.html_safe %><br />
                <% if leaf.has_tags %>
                  <% leaf.tags.each do |tag| %>
                    <a href="/leaves?tagged=<%= tag.name %>">#<%= tag.name %></a>
                  <% end %>
                <% end %>
                <%= link_to "Destroy", leaf, :confirm => 'Are you sure?', :method => :delete %>
              </div>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>

    <div class="leaf-stats">

      <div class="stat-box stat-box1">
        <span class="data"><%= current_user.points %></span>
        <label>Points</label>
      </div>
      <div class="stat-box stat-box2">
        <span class="data"><%= current_user.leaves.size %></span>
        <label>Leaves</label>
      </div>

      <div class="progress-box">
        <label>
          <% if current_user.goal_type == User::DAILY_LEAF_GOAL %>
            Daily Goal Progress: 
            <%= current_user.daily_leaves.size %> / <%= current_user.daily_leaf_goal %>
          <% elsif current_user.goal_type == User::WEEKLY_LEAF_GOAL %>
            Weekly Goal Progress: 
            <%= current_user.weekly_leaves.size %> / <%= current_user.weekly_leaf_goal %>
          <% end %>
        </label>
          <div class="progress radius twelve"><span class="meter" style="width: <%= goal_percentage %>%;"></span></div>
        <% if current_user.goal_type == User::DAILY_LEAF_GOAL %>
          <%= current_user.daily_leaves.size %> / <%= current_user.daily_leaf_goal %>
        <% elsif current_user.goal_type == User::WEEKLY_LEAF_GOAL %>
          <%= current_user.weekly_leaves.size %> / <%= current_user.weekly_leaf_goal %>
        <% end %>
      </div>

      <%= link_to "View more stats! >>", "leaves/stats" %>

    </div>
</div>

<div style="clear:both;"></div>


  

app/views/leaves/new.html.erb
<div class="row">
  <div class="six columns">
    <h2>What are you thankful for today?</h2>
    <%= form_for @leaf, :html => { :multipart => :true } do |form| %>
      <%= form.error_messages %>
      <%= form.text_area :content %>
      <%= form.file_field :photo %><br /><br />
      <%= form.submit 'Done!', :class => 'medium button' %>
      <%= image_tag @leaf.photo.url if @leaf.has_photo %><br />
    <% end %>
  </div>
</div>

app/views/leaves/show.html.erb
<%= image_tag @leaf.photo.url %>

<p>
  <b>Content:</b>
  <%= @leaf.content %>
</p>
 
 
 
<%= link_to 'Edit', edit_leaf_path(@leaf) %> |
<%= link_to 'Back', leaves_path %>

app/views/leaves/stats.html.erb
<div class="row">
  <div class="eight columns">
    <h1>Leaf Statistics</h1>
    <%= high_chart("leaf_count_by_day", @h) %>
  </div>
</div>