config/routes.rb
Gratefuleaf::Application.routes.draw do

  namespace(:admin){ resources :leaves }
  namespace(:admin){ resources :users }

  match '/login' => 'user_sessions#new'
  match '/logout' => 'user_sessions#destroy'
  resources :user_sessions

  resources :users

  match 'leaves/stats' => 'leaves#stats'
  resources :leaves

  root :to => 'landing#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :leaves
  has_many :tags, :through => :leaves
  has_merit

  acts_as_authentic
  attr_accessible :first_name, :last_name, :username, :email, :password, :password_confirmation, :avatar, :goal_type, :daily_leaf_goal, :weekly_leaf_goal, :time_zone
  attr_accessor :password_confirmation

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  extend FriendlyId
  friendly_id :username, use: :slugged

  def has_avatar
    avatar.url != '/avatars/original/missing.png'
  end

  def daily_leaves
    self.leaves.created_today
  end

  def weekly_leaves
    self.leaves.created_this_week
  end


  # goal types: none, daily, or weekly
  NO_LEAF_GOAL = 0
  DAILY_LEAF_GOAL = 1
  WEEKLY_LEAF_GOAL = 2

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to [:admin, @user], :notice => "Successfully created user."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to [:admin, @user], :notice  => "Successfully updated user."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, :notice => "Successfully destroyed user."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
   
    respond_to do |format|
      format.html  # show.html.erb
      format.json  { render :json => @user }
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Registration successful."
      redirect_to root_url
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully updated profile."
      render :action => 'show'
    else
      render :action => 'edit'
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/admin/users/edit.html.erb
<% title "Edit Admin/User" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", [:admin, @user] %> |
  <%= link_to "View All", admin_users_path %>
</p>

app/views/admin/users/index.html.erb
<% title "Admin/Users" %>

<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Username</th>
    <th>Email</th>
    <th>Password</th>
  </tr>
  <% for user in @users %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= user.password %></td>
      <td><%= link_to "Show", [:admin, user] %></td>
      <td><%= link_to "Edit", edit_admin_user_path(user) %></td>
      <td><%= link_to "Destroy", [:admin, user], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Admin/User", new_admin_user_path %></p>

app/views/admin/users/new.html.erb
<% title "New Admin/User" %>

<%= render 'form' %>

<p><%= link_to "Back to List", admin_users_path %></p>

app/views/admin/users/show.html.erb
<% title "Admin/User" %>

<p>
  <strong>First Name:</strong>
  <%= @user.first_name %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <%= link_to "Edit", edit_admin_user_path(@user) %> |
  <%= link_to "Destroy", [:admin, @user], :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", admin_users_path %>
</p>