config/routes.rb
Gratefuleaf::Application.routes.draw do

  namespace(:admin){ resources :leaves }
  namespace(:admin){ resources :users }

  match '/login' => 'user_sessions#new'
  match '/logout' => 'user_sessions#destroy'
  resources :user_sessions

  resources :users

  match 'leaves/stats' => 'leaves#stats'
  resources :leaves

  root :to => 'landing#index'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
  <title><%= content_for?(:title) ? "Gratefuleaf - #{yield(:title)}" : "Gratefuleaf - Be Happier!" %></title>
  
	<!-- Included CSS Files -->
  <link href='http://fonts.googleapis.com/css?family=Original+Surfer' rel='stylesheet' type='text/css'>
	<%= stylesheet_link_tag    "application" %>
	
	<!-- Included JS Files  -->
	<%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="container">
      <div class="row">
        <div class="six columns logo">
          <%= image_tag 'logo1.png', :style => "height: 50px; width: 195px;" %>
          <a href="/" class="owl1"><%= image_tag 'owl.png' %></a>
          <a href="/" class="owl2"><%= image_tag 'owl.png' %></a>
          <a href="/" class="owl3"><%= image_tag 'owl.png' %></a>
          <br />
          <%= image_tag 'branch.png', :style => "margin-left: -30px; margin-top: -30px;" %>
        </div>
        <div class="six columns">
          <ul class="inline-list nav">
            <li class="<%= 'active' if params[:controller] == 'landing' && params[:action] == 'index' %>"><a href="/">Home</a></li>
            <li><a href="#">About</a></li>
            <% if current_user %>
              <li class="<%= 'active' if params[:controller] == 'leaves' %>"><%= link_to "Leaves", '/leaves' %></li>
              <li class="<%= 'active' if params[:controller] == 'users' %>"><%= link_to "My Account", user_path(current_user) %></li>
              <li><%= link_to "Logout", logout_path %></li>
            <% else %>
              <li class="<%= 'active' if params[:controller] == 'users' && params[:action] == 'new' %>"><%= link_to "Signup", new_user_path %></li>
              <li class="<%= 'active' if params[:controller] == 'user_sessions' && params[:action] == 'new' %>"><%= link_to "Login", login_path %></li>
            <% end %>
          </ul>
        </div>
      </div>

    </div>
  </header>

  <%= yield %>

  <% if current_user && (params[:controller] != 'leaves' || params[:action] != 'new') %>
    <div style="margin-bottom: 40px;"></div>
    <div class="toolbar">
      <a class="small button" href="/leaves/new">New Leaf</a>
    </div>
  <% end %>

</body>
</html>